SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    sum(p.PRICE * o.AMOUNT) as TOTAL_SALES
From FOOD_PRODUCT p
join FOOD_ORDER o on p.PRODUCT_ID = o.PRODUCT_ID
where MONTH(o.PRODUCE_DATE) = 5 and YEAR(o.PRODUCE_DATE) = 2022
group by o.PRODUCT_ID
order by TOTAL_SALES DESC, p.PRODUCT_ID ASC