with MAX_SIZE_TABLE as (
select *,
    MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) AS "MAX_SIZE"
from ECOLI_DATA
)
select
    YEAR(DIFFERENTIATION_DATE) AS "YEAR",
    MAX_SIZE - SIZE_OF_COLONY AS "YEAR_DEV",
    ID
from MAX_SIZE_TABLE
order by YEAR, YEAR_DEV