with FISH_MAX_INFO as (
    select
    ID,
    FISH_NAME,
    LENGTH,
    MAX(LENGTH) OVER (PARTITION BY FISH_NAME_INFO.FISH_TYPE) as MAX_LENGTH
from FISH_INFO
join FISH_NAME_INFO on FISH_NAME_INFO.FISH_TYPE = FISH_INFO.FISH_TYPE
)
select 
    ID,
    FISH_NAME,
    LENGTH
from FISH_MAX_INFO
where MAX_LENGTH = LENGTH
order by ID